# Generated by Django 4.2.29 on 2026-06-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
